#
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/setup-go-environment
#
name: Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.7
      - run: go version
      - run: go test ./...
